CREATE DATABASE IF NOT EXISTS ip_database CHARACTER SET utf8;

USE ip_database;

CREATE TABLE IF NOT EXISTS ip_lists (
	ip VARCHAR(100) NOT NULL,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	count INT UNSIGNED DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS blacklist (
	ip VARCHAR(100) NOT NULL,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_munual TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO ip_lists(ip, count) VALUES (
	"111.222.112.33", 1	
);
