USE ip_database;
DELIMITER $$
DROP EVENT IF EXISTS `RESTART_blacklist`$$
CREATE DEFINER=`root`@`localhost` EVENT `RESTART_blacklist` ON SCHEDULE EVERY 1 MINUTE STARTS '2021-05-09 17:00:00' ENDS '2021-06-30 00:00:28' ON COMPLETION NOT PRESERVE ENABLE DO DELETE FROM blacklist
where is_munual='0'$$

DELIMITER ;
